services:
  web-site:
    container_name: web-site
    environment:
      EmailSenderOptions__Email: "[YOUR MAILER EMAIL]"
      EmailSenderOptions__Password: "[YOUR MAILER PASSWORD]"
      ConnectionStrings__DefaultConnectionString: "Server=database;Database=MyAtelierDb;Uid=user;Pwd=password"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8080
    networks:
      - site
    depends_on:
      - database
    command:
      - /bin/sh "dotnet-ef database update && dotnet Presentation.dll"
  database:
    image: mysql
    container_name: database
    restart: always
    environment:
      MYSQL_DATABASE: 'MyAtelierDb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - site

networks:
  site:
    driver: bridge
    name: site
    
volumes:
  mysql-data: